characters = {'0';
'1';
'2';
'3';
'4';
'5';
'6';
'7';
'8';
'9';
'A';
'B';
'C';
'D';
'E';
'F';
'G';
'H';
'I';
'J';
'K';
'L';
'M';
'N';
'O';
'P';
'Q';
'R';
'S';
'T';
'U';
'V';
'W';
'X';
'Y';
'Z';
'a';
'b';
'c';
'd';
'e';
'f';
'g';
'h';
'i';
'j';
'k';
'l';
'm';
'n';
'o';
'p';
'q';
'r';
's';
't';
'u';
'v';
'w';
'x';
'y';
'z';
};

FontNames = {'Agency FB';
'Aharoni';
'Algerian';
'Andalus';
'Angsana New';
'AngsanaUPC';
'Arabic Typesetting';
'Arial';
'Arial Black';
'Arial Narrow';
'Arial Rounded MT';
'Arial Unicode MS';
'AvantGarde';
'Baskerville Old Face';
'Batang';
'BatangChe';
'Bauhaus';
'Bell MT';
'Berlin Sans FB';
'Berlin Sans FB Demi';
'Bernard MT Condensed';
'Bitstream Vera Sans';
'Bitstream Vera Sans Mono';
'Bitstream Vera Sans Mono Oblique';
'Bitstream Vera Sans Oblique';
'Bitstream Vera Serif';
'Blackadder ITC';
'Bodoni MT';
'Bodoni MT Black';
'Bodoni MT Condensed';
'Bodoni MT Poster Compressed';
'Book Antiqua';
'Bookman';
'Bookman Old Style';
'Bookshelf Symbol';
'Bradley Hand ITC';
'Britannic';
'Broadway';
'Browallia New';
'BrowalliaUPC';
'Brush Script MT';
'Calibri';
'Californian FB';
'Calisto MT';
'Cambria';
'Cambria Math';
'Candara';
'Castellar';
'Centaur';
'Century';
'Century Gothic';
'Century Schoolbook';
'Chiller';
'Colonna MT';
'Comic Sans MS';
'Consolas';
'Constantia';
'Cooper Black';
'Copperplate Gothic';
'Copperplate Gothic Light';
'Corbel';
'Cordia New';
'CordiaUPC';
'Courier';
'Courier New';
'Curlz MT';
'DaunPenh';
'David';
'DFKai-SB';
'DilleniaUPC';
'DokChampa';
'Dotum';
'DotumChe';
'Edwardian Script ITC';
'Elephant';
'Engravers MT';
'Eras';
'Eras Demi ITC';
'Eras Light ITC';
'Eras Medium ITC';
'Estrangelo Edessa';
'EucrosiaUPC';
'Euphemia';
'FangSong';
'Felix Titling';
'Footlight MT Light';
'Forte';
'Franklin Gothic Book';
'Franklin Gothic Demi';
'Franklin Gothic Demi Cond';
'Franklin Gothic Heavy';
'Franklin Gothic Medium';
'Franklin Gothic Medium Cond';
'FrankRuehl';
'FreesiaUPC';
'Freestyle Script';
'French Script MT';
'Garamond';
'Gautami';
'Georgia';
'Gigi';
'Gill Sans MT';
'Gill Sans MT Condensed';
'Gill Sans MT Ext Condensed';
'Gill Sans Ultra';
'Gisha';
'Gloucester MT Extra Condensed';
'Goudy Old Style';
'Goudy Stout';
'Gulim';
'GulimChe';
'Gungsuh';
'GungsuhChe';
'Haettenschweiler';
'Harlow Solid';
'Harrington';
'Helvetica';
'Helvetica-Narrow';
'High Tower Text';
'Impact';
'Imprint MT Shadow';
'Informal Roman';
'IrisUPC';
'Iskoola Pota';
'JasmineUPC';
'Jokerman';
'Juice ITC';
'KaiTi';
'Kalinga';
'Kartika';
'KodchiangUPC';
'Kristen ITC';
'Kunstler Script';
'Latha';
'Leelawadee';
'Levenim MT';
'LilyUPC';
'Lucida Bright';
'Lucida Bright Demibold';
'Lucida Calligraphy';
'Lucida Console';
'Lucida Fax';
'Lucida Fax Demibold';
'Lucida Fax Regular';
'Lucida Handwriting';
'Lucida Sans';
'Lucida Sans Demibold';
'Lucida Sans Demibold Roman';
'Lucida Sans Regular';
'Lucida Sans Typewriter';
'Lucida Sans Typewriter Oblique';
'Lucida Sans Typewriter Regular';
'Lucida Sans Unicode';
'Magneto';
'Maiandra GD';
'Malgun Gothic';
'Mangal';
'Matura MT Script Capitals';
'Meiryo';
'Microsoft Himalaya';
'Microsoft JhengHei';
'Microsoft Sans Serif';
'Microsoft Uighur';
'Microsoft YaHei';
'Microsoft Yi Baiti';
'MingLiU';
'MingLiU-ExtB';
'MingLiU_HKSCS';
'MingLiU_HKSCS-ExtB';
'Miriam';
'Miriam Fixed';
'Mistral';
'Modern';
'Modern No.';
'Mongolian Baiti';
'Monotype Corsiva';
'MoolBoran';
'MS Gothic';
'MS Mincho';
'MS PGothic';
'MS PMincho';
'MS Reference Sans Serif';
'MS Sans Serif';
'MS Serif';
'MS UI Gothic';
'MV Boli';
'Narkisim';
'NewCenturySchoolBook';
'Niagara Engraved';
'Niagara Solid';
'Nina';
'NSimSun';
'Nyala';
'OCR A Extended';
'Old English Text MT';
'Onyx';
'OpenSymbol';
'Palace Script MT';
'Palatino';
'Palatino Linotype';
'Papyrus';
'Parchment';
'Perpetua';
'Perpetua Titling MT';
'Perpetua Titling MT Light';
'Plantagenet Cherokee';
'Playbill';
'PMingLiU';
'PMingLiU-ExtB';
'Poor Richard';
'Pristina';
'Raavi';
'Rage';
'Ravie';
'Rockwell';
'Rockwell Condensed';
'Rockwell Extra';
'Rod';
'Roman';
'Script';
'Script MT';
'Segoe Print';
'Segoe Script';
'Segoe UI';
'Showcard Gothic';
'Shruti';
'SimHei';
'Simplified Arabic';
'Simplified Arabic Fixed';
'SimSun';
'SimSun-ExtB';
'Small Fonts';
'Snap ITC';
'Stencil';
'Sylfaen';
'Symbol';
'Tahoma';
'Tempus Sans ITC';
'Times';
'Times New Roman';
'Traditional Arabic';
'Trebuchet MS';
'Tunga';
'Tw Cen MT';
'Tw Cen MT Condensed';
'Tw Cen MT Condensed Extra';
'Verdana';
'Viner Hand ITC';
'Vivaldi';
'Vladimir Script';
'Vrinda';
'Wide Latin';
'ZapfChancery';
'ZapfDingbats';
};

FontWeights = {'normal';
'bold';
};

FontAngles = {'normal';
'italic';
};

